sudo: false  # travis container-based infrastructure

language: python

python:
  - "2.7"
  - "3.4"

# Set up anaconda
before_install:
  # Example yml file didn't set sudo to false above,
  # and had the next line uncommented
#  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
#  - chmod +x miniconda.sh
#  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  # Update conda itself
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
install:
  - conda create --yes --name=tonic_test_env python=$TRAVIS_PYTHON_VERSION --file=ci/requirements-$TRAVIS_PYTHON_VERSION.txt
  - source activate tonic_test_env
  - python setup.py install

# command to run tests
script:
  - which python
  - python --version
  - conda list
  - pip freeze
  - echo $PATH
  - vic_utils -h
  - py.test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0b751ac59ea833728a02
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
